classes:

- service.keepalived.cluster.single
- system.linux.system.repo.mcp.openstack
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.saltstack.xenial
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.glusterfs.server.cluster
- system.salt.control.virt
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.cluster.openstack_telemetry_cluster
- system.salt.control.cluster.stacklight_server_cluster
- system.salt.control.cluster.stacklight_log_cluster
- system.salt.control.cluster.stacklight_telemetry_cluster
- cluster.physical_mcp10_dvr
parameters:
  _param:
    cluster_vip_address: ${_param:infra_compute_address}
    cluster_node01_address: ${_param:infra_compute_node01_address}
    cluster_node02_address: ${_param:infra_compute_node02_address}
    cluster_node03_address: ${_param:infra_compute_node03_address}
    keepalived_vip_interface: br-ctl
    keepalived_vip_virtual_router_id: 69
    deploy_nic: eth0
    primary_first_nic: eth1
    primary_second_nic: eth2
  salt:
    control:
      size:
      # Default production sizing
        openstack.control:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 4
          ram: 8192
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 4
          ram: 4096
          disk_profile: small
          net_profile: default
        openstack.telemetry:
          cpu: 4
          ram: 4096
          disk_profile: xxlarge
          net_profile: default
        openstack.proxy:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 4
          ram: 4096
          disk_profile: small
          net_profile: default
        opencontrail.analytics:
          cpu: 4
          ram: 4096
          disk_profile: large
          net_profile: default
        stacklight.log:
          cpu: 2
          ram: 4096
          disk_profile: xxlarge
          net_profile: default
        stacklight.server:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: default
        stacklight.telemetry:
          cpu: 2
          ram: 4096
          disk_profile: xxlarge
          net_profile: default
      cluster:
        internal:
          node:
            prx02:
              provider: kvm03.${_param:cluster_domain}

  virt:
    nic:
      default:
        eth1:
          bridge: br-mgm
          model: virtio
        eth0:
          bridge: br-ctl
          model: virtio

  linux:
    network:
      interface:
        eth0:
          enabled: true
          proto: manual
          type: eth
          mtu: 1500
        eth1:
          enabled: true
          type: eth
          proto: manual
          master: bond0
          type: slave
          mtu: 1500
        eth2:
          enabled: true
          type: eth
          proto: manual
          master: bond0
          type: slave
          mtu: 1500
        bond0:
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - ${_param:primary_first_nic}
          - ${_param:primary_second_nic}
          slaves: ${_param:primary_first_nic} ${_param:primary_second_nic}
          mode: active-backup
          mtu: 1500
        bond0.2402:
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - bond0
          mtu: 1500
        bond0.2403:
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - bond0
        br-mgm:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:deploy_address}
          netmask: 255.255.255.192
          gateway: 172.16.164.1
          use_interfaces:
          - eth0
        br-ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
          use_interfaces:
          - bond0.2402
          name_servers:
          - 8.8.8.8
          - 8.8.4.4
        br-data:
          enabled: true
          type: bridge
          proto: manual
          use_interfaces:
          - bond0.2403
    system:     
      user:
        root:
          enabled: true
          name: root
          home: /root
          # Password is cloudlab, comment out, configure your SSH key bellow
          # and disable password auth
          password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./
