classes:
- cluster.physical_mcp10_dvr

parameters:
  linux:
    system:     
      user:
        root:
          enabled: true
          name: root
          home: /root
          # Password is cloudlab, comment out, configure your SSH key bellow
          # and disable password auth
          password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./