classes:
- system.linux.system.repo.mcp.salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.master.api
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
- cluster.physical_mcp10_master
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/mceloud/physical_mcp10_opencontrail-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    salt_master_host: ${_param:infra_config_address}
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
  salt:
    master:
      accept_policy: open_mode
      order_masters: True
